src/layouts/StatsLayout.vue
src/views/Stats/Item.vue
src/views/Stats/Stage.vue

the statistics table will now be able to response to all the clicks in a particular row of object
and be able to redirect the user to the specified object's statistics page
resolved #4

feat(stat-tables): expanded the clicking area of the statistics table

---

src/views/Stats/Item.vue
src/views/Stats/Stage.vue

It will now show the name on both the stepper component and also as a title on the page
fixed #5

feat(stat-tables): show the name of the selected object on result page

---

package.json
src/components/Charts.vue
src/views/Stats/Item.vue

- fix(charts.vue): fix 0 value skip issue
- feat(item.vue): add item page drop rate graph

Fix charts data skip 0 issue and add Item page charts #16

---

src/views/Stats/Item.vue

refine item page layout that display item with multi-column
#31

feat(item.vue): refine item page layout #31

---

src/App.vue
src/components/AccountManager.vue
src/locales/en.json
src/locales/zh.json
src/models/_common.js
src/models/index.js
src/models/items.js
src/store.js
src/utils/objectManager.js
src/utils/service.js

* Fixed #28, #33, #34
* Optimized `objectManager`
* Isolated `AccountManager` from `App.vue`

Fix several issues

---

src/components/Item.vue
src/components/ItemIcon.vue
src/views/Stats/Item.vue

show 4 columns for devices whose width is between 360 and 414; move 3003 to the end of the list; do
not show item name
fix #39

feat(item.vue): refine item page layout

---

src/views/About/Members.vue

Feat collaborators

---

src/views/Stats/Item.vue
src/views/Stats/Stage.vue

add condition to alt-labels
fix #41

fix(stepper): only show alt-labels under xs

---

src/views/Report.vue

forgot to fix the stepper on report page for #41

fix(stepper): fix stepper clickable area too large issue in report page

---

src/views/About/Changelog.vue
src/views/About/Contact.vue
src/views/About/Contribute.vue
src/views/About/Donate.vue
src/views/About/Links.vue
src/views/About/Members.vue
src/views/Home.vue

Refine Home/Changelog/Contribute/Donate/Links/Members page
fix #15

feat(home): migrate old static pages to the new site

---

src/models/_common.js
src/models/index.js
src/models/items.js
src/models/limitations.js
src/models/matrices/base.js
src/models/matrices/globalMatrix.js
src/models/matrices/personalMatrix.js
src/models/stages.js
src/models/zones.js
src/utils/objectManager.js

ObjectManager is intended to be an Object Life-cycle manager that automatically fetches data when passed object's TTL; besides that, it also provides getter API which eventually acts as a proxy between the dependency and the object data storage.
EXPECT BREAKING CHANGES: the `Getters` API under `src/utils/getters.js` will be deprecated after the usage of such utility. The `Getters` API **will** be removed in future versions, so contributors should migrate their data source API to such new provider.

feat(objectmanager): implemented the objectManager

---

src/App.vue
src/components/ItemIcon.vue
src/router.js

- fix(itemicon.vue): remove icon change transition
- feat(app.vue): do not open the menu by default on mobile view#61

Fix #52 and #61 about item icon and app menu

---

package.json
src/components/Charts.vue
src/vendors/plotly.js
yarn.lock

reduced the size of module `plotly.js` by using a-la-carte method of using the library
fix #64

ci(travis): fixed #64

---

src/App.vue
src/components/ItemStepper.vue
src/utils/service.js

fix(itemstepper): fix itemstepper style

---

src/components/AccountManager.vue
src/router.js
src/views/Stats/Item.vue
src/views/Stats/Stage.vue

- fix(route): fix #60 about auto scroll to top after routing  …
- fix(accountmanager.vue): fix #55 about logout dialog not disappar  …
- fix(stage): fix #57 item/stage page double click issue  …

Fix issue #55 #60 #57

---

src/components/ItemStepper.vue
src/views/Report.vue

1. remove + and -
2. increase by left click and reduce by right click
3. add clear button to reset
fix #27 
will implement i18n stuff in separate branch

feat(report): refine report page

---

src/App.vue
src/components/AccountManager.vue
src/components/DataSourceToggle.vue
src/components/ItemIcon.vue
src/main.js
src/models/limitations.js
src/models/matrices/base.js
src/models/matrices/globalMatrix.js
src/models/matrices/personalMatrix.js
src/models/stages.js
src/models/trends.js
src/models/zones.js
src/store.js
src/utils/getters.js
src/utils/objectManager.js
src/views/Stats/Item.vue
src/views/Stats/Stage.vue

- refactor(objectmanager): refine object maneger use it to fetch data
- feat(datasourcetoggle.vue): add data source toggle to switch data source

Feat 21 switch data source #21

---

src/components/ItemStepper.vue
src/views/Report.vue

check user selected items on submit
fix #29

fix(report.vue): fix limitation bug

---

src/App.vue
src/config/index.js
src/locales/en.json
src/locales/zh.json
src/main.js
src/router.js

change the page title according its actual page title, while also complies with i18n
fix #76

fix(router): change the page title according its actual page title

---

src/views/Report.vue

fix(report.vue): auto login after report

---

src/App.vue
src/store.js

feat(app.vue): add refresh data button

---

src/views/Report.vue
src/views/Stats/Stage.vue

1. in report zone selection page, we make ACTIVITY as the first category to show, and do not show
closed zones
2. in result zone selection page, we make opening ACTIVITY as the first category,
closed as the last one to show
fix #96

feat(zones): change zones sequence

---

src/views/Report.vue

fix(report.vue): refine undo report action

---

src/App.vue
src/components/AccountManager.vue
src/main.js
src/router.js
src/views/About/Links.vue
src/views/Report.vue

define some ga events and log them
fix #92

feat(ga): integrate with ga

---

src/App.vue

update title when switching language
fix #105

fix(title): update title when switching language

---

src/App.vue
src/router.js

fix(route.js): fix log planner issue

---

src/components/RandomBackground.vue

to reduce data consumption on both the user side and the cdn side

fix(randombackground): use webp + jpg fallback for the background

---

src/components/RandomBackground.vue
vue.config.js

feat(randomimage): easter egg!

---

src/App.vue

improvement(i18n): improved `ja` font

---

package.json
src/store/index.js
yarn.lock

fix(store): use compression now

---

src/components/global/GlobalSnackbar.vue
src/components/stats/StageSelector.vue
src/components/toolbar/AccountManager.vue
src/locales/en.json
src/views/About/Bulletin.vue
src/views/About/Contact.vue
src/views/About/Contribute.vue
src/views/About/Donate.vue
src/views/About/Intro.vue
src/views/Report.vue

Quick pass over the English translation to make it sound more natural.

English translation pass

---

package.json
src/config/index.js
src/views/About/Changelog.vue

Hotfix 1.1.10

---

README.md

chore(readme): add saucelabs badge

---

src/config/index.js

fix(config): toooooooooo large!

---

src/components/advancedQuery/selectors/QuerySelectorStage.vue
src/components/stats/MultiStageSelector.vue

fix(stageselector): add permanent activity stages

---

src/locales/ko.yml

Based on en.yml and the original kr.yml. Also referred to zh.yml a bit

KR Localization

---

src/locales/ja.yml

Translated the resetting part of ARKPLANNER to Japanese.

Translate to Japanese

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/io/penguinstats/app/AndroidUtils.java
android/app/src/main/java/io/penguinstats/app/PGSApplication.java
android/app/src/main/res/values/styles.xml
android/build.gradle

fix 2 icons issue
add method to get system dark mode status

fix android issue

---

src/locales/archived/zh.js
src/locales/archived/zh.json
src/locales/archived/zh_CN_x_seaborn.json
src/locales/zh_CN.json
src/locales/zh_CN_x_seaborn.json

修复残阳章节原为9~11章的bug，更新到9~12章
fixes #557

fix: issue #557 main action update dying sun 9~12
